### ISSUE TITLE
Breakpoint during shadow DOM implementation 

### ISSUE THREAD

**Issue by D0ugla5MB** [D0ugla5MB/Bugigangas#4]
https://github.com/D0ugla5MB/Bugigangas/blob/cc878bf5f72ae6a396b725169efca6259edec492/modules/router.js#L10

# **Breakpoint during Shadow DOM implementation**

## **Description**  
Errors occur when navigating between pages during Shadow DOM implementation. The following are the issues encountered:

## **Steps to Reproduce**
1. Navigate to `/home/home.html`.
2. Navigate to `/#`.
3. Navigate to `/#home`.

### **1. Trying to navigate to `/home/home.html` triggers:**  
> Uncaught TypeError: Cannot read properties of null (reading 'attachShadow')
>     at `loadContent` (router.js:28:32)
>     at HTMLDocument.<anonymous> (`app.js`:16:5)

### **2. Trying to navigate to `/#` triggers:**  
> Refused to apply style from '/home.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### **3. Trying to navigate to `/#home` triggers:**  
> Uncaught NotSupportedError: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.
>     at loadContent (`router`.js:28:32)

**Comment by D0ugla5MB** [comment]
Resolved by changing Shadow DOM to ES6 import/exports modules structure.
